name = "holostack-pso-cron"
main = "index.js"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["* * * * *"]

[vars]
BASE_URL = "https://holostack.holostack.workers.dev"
